### ISSUE TITLE
GEO index does not work, appears to be corrupted

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#331] opened 2024-10-22 20:39 UTC
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did [...] action, I noticed [...]

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

details to be provided by @tloubrieu-jpl @ale

**Comment by alexdunnjpl** [comment] 2024-10-22 23:41
Working this with AWS support

**Comment by alexdunnjpl** [comment] 2024-10-22 23:49
Issue magically resolved the second I got on a call with escalated support (last checked ~45min ago).

Support indicated that the failure was occurring during fetch phase, which is not logged by default.  They have enabled logging for that phase, so that if this occurs again, root-cause analysis is available.

Support ticket is considered resolved.  Closing on that basis.

**Closed by alexdunnjpl** 2024-10-22 23:49 UTC
Labels: B15.1, bug, sprint-backlog, s.critical

**Comment by tloubrieu-jpl** [comment] 2024-10-22 23:52
Thanks @alexdunnjpl !!! Great news.
However I don't understand a word from the cause of the failure. We can have a short huddle on that tomorrow.

**Comment by c-suh** [comment] 2025-05-16 21:28
@tloubrieu-jpl and @jordanpadams do you still want me to test this for I&T? If so, I will need access to the production environment.

**Comment by jordanpadams** [comment] 2025-05-16 22:10
@c-suh no. i&t.skip added

**Comment by jordanpadams** [comment] 2025-05-16 22:11
The fact that is working now indicates it is fixed.
