### ISSUE TITLE
archive status value was not changed on bundle's contents

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/registry#118] opened 2022-10-10 21:12 UTC
## 🐛 Describe the bug

When changing a bundle's archive status to archives, the following error was displayed
[ERROR] Expected BEGIN_ARRAY but was STRING at line 1 column 166 path $._source.ref_lid_collection

## 📜 To Reproduce

1. Set OPENSEARCH_URL to 

https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com:443
or equivalent

2. Set AUTH_FILE to your authorization credentials file

3. Run a command similar to 

registry-manager set-archive-status -status archived -lidvid "urn:nasa:pds:epoxi_mri::1.0" -es $OPENSEARCH_URL -auth $AUTH_FILE -l epoxi_mri_status.log

4. see error
[ERROR] Expected BEGIN_ARRAY but was STRING at line 1 column 166 path $._source.ref_lid_collection

## 🕵️ Expected behavior

All the products in the bundle to be set to archive status archived OR 
documentation on how to make that happen without needing to 
set the value for every product.

## 🩺 Test Data / Additional context

The log file's connect were

2022-10-10 16:09:19,741 [INFO] Setting product status. LIDVID = urn:nasa:pds:epo
xi_mri::1.0, status = archived

## 🖥 System Info
Linux

n/a

---

## ⚙️ Engineering Details
See related registry manager issue here: https://github.com/NASA-PDS/registry-mgr/issues/57

**Comment by alexdunnjpl** [comment] 2022-11-10 19:53
@plawton-umd have you ever successfully run a command like this on a single lidvid?

**Comment by plawton-umd** [comment] 2022-11-10 20:37
@alexdunnjpl This was the first time I ran the upload to the registry.  Anne ran the previous uploads and said she did not have to do this step (changing from staged to archived).

**Comment by jordanpadams** [comment] 2022-11-15 18:39
@alexdunnjpl https://github.com/NASA-PDS/registry-mgr/issues/57 is a duplicate of the same error @plawton-umd is encountering here.

**Comment by alexdunnjpl** [comment] 2022-11-22 18:35
@tloubrieu-jpl this is in-prog, and will likely require a fix to `harvest`. I'll jump to slack for further discussion

**Comment by alexdunnjpl** [comment] 2022-11-23 03:30
[See corresponding issue in `registry-common`](https://github.com/NASA-PDS/registry-common/issues/29)

**Comment by alexdunnjpl** [comment] 2022-12-01 18:38
Fixed in [NASA-PDS/registry-common Issue 30](https://github.com/NASA-PDS/registry-common/pull/30)

@tloubrieu-jpl @jimmie what's the process for getting this out to @plawton-umd ?  Have her wait for the next release and update then, or is there a more expedient way?

**Closed by alexdunnjpl** 2022-12-01 18:38 UTC
Labels: B13.1, bug, s.high, sprint-backlog

**Comment by gxtchen** [comment] 2023-04-20 04:44
@tloubrieu-jpl What is the docker equivalent for these two steps?
Set OPENSEARCH_URL to

[https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com:443](https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com/)
or equivalent

    Set AUTH_FILE to your authorization credentials file

**Comment by tloubrieu-jpl** [comment] 2023-04-20 16:59
Hi @gxtchen ,

To use registry-manager with the docker compose setup, you must:
1. add `elasticsearch` to your /etc/hosts file as a localhost alias (on macOS, linux). 

    127.0.0.1       localhost
    127.0.0.1       elasticsearch 
 
For windows I don't know the equivalent but there is one.

2. the opensearch url is going to be `https://elasticsearch:9200/`
3. the default login/password are admin/admin. You can find one auth.cfg file in folder docker/default-config of the registry repository (as linked by @alexdunnjpl in his comment above)
