### ISSUE TITLE
registry docker not getting out of "waiting for elasticsearch"

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/registry#77] opened 2022-07-14 06:32 UTC
## 🐛 Describe the bug identified during I&T
launch docker with command docker compose --profile=int-registry-service-loader up
waited for more than 15 minutes, the command was still printing out "waiting for elasticsearch"

## 🔁 : Related issues
https://github.com/nasa-pds/registry/issues/69

---

### 📜 To Reproduce
1. git clone https://github.com/NASA-PDS/registry.git
2. cd docker/certs
3. ./generate-certs.sh
4. cd ..
5. docker compose --profile=int-registry-service-loader up

### 🖥 System Info

---

## ⚙️ Engineering Details
[int-reg-service-loader.log](https://github.com/NASA-PDS/registry/files/9109151/int-reg-service-loader.log)

**Comment by ramesh-maddegoda** [comment] 2022-07-23 00:36
@gxtchen, I  executed the following steps.

1. git clone https://github.com/NASA-PDS/registry.git
2. cd docker/certs
3. ./generate-certs.sh
4. cd ..
5. docker compose --profile=int-registry-service-loader up

And the above process executed with the expected outcome. Please see the log file attached herewith.
[https://app.zenhub.com/files/419869439/d6be8292-33be-407f-8dd6-ef4a87b5cd80/download](https://app.zenhub.com/files/419869439/d6be8292-33be-407f-8dd6-ef4a87b5cd80/download)


We noticed a similar issue with another user and finally found-out that the Elasticsearch/opensearch docker container is crashing on that laptop after few minutes. As a result, the other docker containers were waiting for Elasticsearch. It appeared that it is problem related with the docker resource consumption on that laptop.


- Can you please check if the Elasticsearch docker container is up and running (check docker desktop), while you see this waiting for elasticsearch?

- Can you please also try the following 2 commands and see the output?
 
 ```
docker compose --profile=int-registry-service-loader down
docker compose --profile=int-registry-batch-loader up
```

You should see an output similar to the following table towards the end of the log.

![Screen Shot 2022-07-22 at 5.35.05 PM.png](https://images.zenhubusercontent.com/618d986498c9bb185f49e721/0b1d8324-3c0b-4677-94ab-b9f8e0822c62)

**Comment by gxtchen** [comment] 2022-07-25 05:39
@tloubrieu-jpl  @ramesh-maddegoda after re-cloning registry.git, I don't see the "waiting for elasticsearch" message any more.
But I can't connect to [the swagger](http://localhost:8080/swagger-ui.html)

I got this message:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Mon Jul 25 05:17:51 UTC 2022
There was an unexpected error (type=Not Found, status=404).

**Comment by tloubrieu-jpl** [comment] 2022-07-25 14:35
Hi @gxtchen 

That works for me. Are you using the latest version of the registry (did you `git pull` from the repository lately).

The swagger ui access has been fixed in a recent update of Al so this is in the docker image nasapds/registry-api-service:latest that should be pulled by the docker compose script.

**Comment by ramesh-maddegoda** [comment] 2022-07-25 19:34
@gxtchen, I can see that you have used http://localhost:8080/swagger-ui.html to access the Swagger.

Can you please try http://localhost:8080/swagger-ui/index.html ?

**Comment by jordanpadams** [comment] 2022-08-10 16:02
@gxtchen can you confirm if this is an issue or not?

**Comment by gxtchen** [comment] 2022-08-11 05:39
@jordanpadams @ramesh-maddegoda even with the latest version, I can't get to the swagger-ui. 
both http://localhost:8080/swagger-ui/index.html and http://localhost:8080/swagger-ui.html gives the same error
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Aug 11 05:37:26 UTC 2022
There was an unexpected error (type=Not Found, status=404).

**Comment by ramesh-maddegoda** [comment] 2022-08-18 20:33
@jordanpadams, can we close this issue, because we do not have the"waiting for elasticsearch" error anymore? 

If required, we can create a new issue for the the Swagger-UI loading issue (Whitelabel Error Page) reported by @gxtchen above (if that error is not already captured in another issues). Also, I am unable to reproduce the "Whitelabel Error Page" of Swagger-ui with the latest Registry API docker image.

**Comment by jordanpadams** [comment] 2022-08-19 14:32
@gxtchen @ramesh-maddegoda let's close this as invalid/wontfix and let's just move on with the latest version of the registry. At this point in the build cycle, there is no point in belaboring testing with a hotfix version, when we will be releasing a new version of these tools in the near term

**Closed by jordanpadams** 2022-08-19 14:32 UTC
Labels: B12.1, I&T, bug, s.low, sprint-backlog
