### ISSUE TITLE
Document how to request the staged products in the registry

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#82] opened 2022-07-29 02:44 UTC
## 💡 Description

Initial request from Dan Scholes 

Add the exact opensearch in the documentation.

**Comment by jordanpadams** [comment] 2022-10-06 17:31
Duplicate of https://github.com/NASA-PDS/registry/issues/100

**Closed by jordanpadams** 2022-10-06 17:31 UTC
Labels: B13.0, skip-i&t, sprint-backlog, task
